### PR TITLE
update SLS APIs to latest

### PR DESCRIPTION
**Pull request by daxingplay**
Hi, I changed SLS APIs to match latest docs. I also added all the test cases for SLS APIs

Below is the detail of APIs I changed.

😆 indicates that the API is missing, so I added it.
💉 indicates that the API is removed, so I also removed it.

`listTopics` and `Index` related APIs are not listed in the doc, but I tested them and worked, so I left them as they were.

| group | SLS Java SDK | aliyun-sdk-js | Aliyun SLS Docs |
|-------|------|------|------ |
| Config | List | 😆 |  ✔️ |
| Config | Create |😆 | ✔️ |
| Config | Delete | 😆 | ✔️ |
| Config | Get  |  😆 | ✔️ |
| Config | Update | 😆  | ✔️ |
| Config | GetAppliedMachineGroups | 😆   | ✔️ |
| MachineGroup | List | 😆 | ✔️ |
| MachineGroup | Create | 😆 | ✔️ |
| MachineGroup | Delete | 😆 | ✔️ |
| MachineGroup | Get | 😆 | ✔️ |
| MachineGroup | Update | 😆 | ✔️ |
| MachineGroup | GetAppliedConfigs  | 😆 | ✔️ |
| MachineGroup |                     | 😆 | ApplyConfigToMachineGroup |
| MachineGroup |          | 😆 | RemoveConfigFromMachineGroup|
| MachineGroup |       |  😆 | ListMachines |
| LogStore | List | listLogStores| ✔️ |
| LogStore | Create |createLogstore | ✔️ |
| LogStore | Delete |deleteLogstore | ✔️ |
| LogStore | Get | getLogstore| ✔️ |
| LogStore | Update | updateLogstore| ✔️ |
| LogStore | GetLogs | getLogs | ✔️ |
| LogStore | GetHistograms | getHistograms| ✔️ |
| Topics |            |  listTopics  | Not Listed |
|  Shipper | GetShipperStatus  | 😆 | ✔️ |
|  Shipper | RetryShipperTask| 😆 | ✔️ |
| Shard | List | listShards| ✔️ |
| Shard | Split | splitShard| ✔️ |
| Shard | Merge | mergeShards| ✔️ |
| Shard | PutLogStoreLogs | putLogs | ✔️ |
| Shard |           |  💉deleteShard | Not Supported |
| Shard | GetCursor | getCursor| ✔️ |
| Shard | PullLogs | batchGetLogs | ✔️ |
| Index  |      | createIndex |Not Listed |
| Index |      |  updateIndex |Not Listed |
| Index |      |  deleteIndex |Not Listed |
| Index |      |  getIndex |Not Listed |

### CODE REVIEW

**Comment by daxingplay** [comment]
But I also found some inconsistent API definitions in current version.

For example, some `input` use `logStoreName`, some use `logstoreName`.

Since those might be used by users, I did not change them.

**Comment by mariodu** [comment]
+1

**Comment by mariodu** [comment]
👍

**Comment by mariodu** [comment]
可以更新下 API 版本，官方文档最近更新是 2017-10-23，https://help.aliyun.com/document_detail/29007.html。这样就可以把一些含糊不清的定义处理下。

**Comment by mayunlei** [comment]
@daxingplay  thanks for your excellent work👍

**Comment by mariodu** [comment]
@mayunlei 建议统一下 api 参数，比如 @daxingplay 提到的 logStoreName 和 logstoreName 问题

**Pull request merged**
